name: Crandall and Associates
favicon: null
layout_spectrum: 0.7945299516431987
typography_spectrum: 0.3898543524555862
title: Crandall and Associates
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8921357896178961
  lightness: 0.10288918344303966
  saturation: 0.07916506193578243
  rhythmicContrast: 0.5668486140202731
purpose: []
